export const RECEIVE_PREVIOUS_HOSPITALIZATIONS = 'RECEIVE_PREVIOUS_HOSPITALIZATIONS';
export const CLEAR_PREVIOUS_HOSPITALIZATIONS = 'CLEAR_PREVIOUS_HOSPITALIZATIONS';
export const FETCH_ERROR = 'FETCH_ERROR';

export const RECEIVE_HEALTHPLANS = 'RECEIVE_HEALTHPLANS';
export const RECEIVE_FACILITIES = 'RECIEVE_FACILITIES';
export const RECEIVE_MEMBERS = 'RECEIVE_MEMBERS';
export const RECEIVE_DICT_FORMS = 'RECEIVE_DICT_FORMS';
export const RECEIVE_DICT_FORM = 'RECEIVE_DICT_FORM';
export const RECEIVE_MEMBER_FORM_HEADERS = 'RECEIVE_MEMBER_FORM_HEADERS';
export const RECEIVE_ACTIVE_ACUTE_TRANSFERS = 'RECEIVE_ACTIVE_ACUTE_TRANSFERS';
export const RECEIVE_SKILLED_SERVICES = 'RECEIVE_SKILLED_SERVICES';


export const SET_SELECTED_HEALTHPLAN = 'SET_SELECTED_HEALTHPLAN';
export const SET_SELECTED_FACILITY = 'SET_SELECTED_FACILITY';
export const SET_SELECTED_PATIENT = 'SET_SELECTED_PATIENT';
export const SET_SELECTED_DICT_FORM = 'SET_SELECTED_DICT_FORM';
export const SET_SIDEBAR_NAV = 'SET_SIDEBAR_NAV';
export const SET_CURRENT_MEMBER_FORM = 'SET_CURRENT_MEMBER_FORM';
export const RECEIVE_AND_SET_CURRENT_MEMBER = 'RECEIVE_AND_SET_MEMBER';

export const SET_LOADING_TRUE ='SET_LOADING_TRUE';
export const SET_LOADING_FALSE = 'SET_LOADING_FALSE';

export const SET_FORM_LOADING_TRUE ='SET_FORM_LOADING_TRUE';
export const SET_FORM_LOADING_FALSE = 'SET_FORM_LOADING_FALSE';

export const SET_SAVING_TRUE = 'SET_SAVING_TRUE';
export const SET_SAVING_FALSE = 'SET_SAVING_FALSE';

export const TOGGLE_DICT_FORM_DIALOG = 'TOGGLE_DICT_FORM_DIALOG';
export const TOGGLE_MEMBER_SELECTOR = 'TOGGLE_MEMBER_SELECTOR';
export const TOGGLE_ACUTE_MODAL = 'TOGGLE_ACUTE_MODAL';
export const TOGGLE_SKILLED_MODAL = 'TOGGLE_SKILLED_MODAL';
export const CLOSE_MEMBER_SELECTOR = 'CLOSE_MEMBER_SELECTOR';



export const SHOW_MEMBER_FORM_EDITOR = 'SHOW_MEMBER_FORM_EDITOR';
export const HIDE_MEMBER_FORM_EDITOR = 'HIDE_MEMBER_FORM_EDITOR';

export const SHOW_MEMBER_FORM_VIEWER = 'SHOW_MEMBER_FORM_VIEWER';
export const HIDE_MEMBER_FORM_VIEWER = 'HIDE_MEMBER_FORM_VIEWER';


export const SHOW_MEMBER_FORM_DIRECTOR_VIEWER = 'SHOW_MEMBER_FORM_DIRECTOR_VIEWER';
export const HIDE_MEMBER_FORM_DIRECTOR_VIEWER = 'HIDE_MEMBER_FORM_DIRECTOR_VIEWER';

export const REGISTER_USER = 'REGISTER_USER';
export const SAVE_MEMBER_FORM = 'SAVE_MEMBER_FORM';



export const FETCH_FACILITY_BY_NPI = 'FETCH_FACILITY_BY_NPI';
export const SEARCH_FACILITY_BY_NAME = 'SEARCH_FACILITY_BY_NAME';

export const CLEAR_FACILITY_SEARCH_RESULTS = 'CLEAR_FACILITY_SEARCH_RESULTS';

export const SET_CURRENT_MEMBER_FORM_DATA = 'SET_CURRENT_MEMBER_FORM_DATA';
export const RECEIVE_MEMBER_FORM = 'RECEIVE_MEMBER_FORM';


